server:
  port: 8080

logging:
  level:
    com.sxs: debug
spring:
  redis:
    host: 124.221.229.116
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0

